import React from 'react';

const Bar: React.FC = () => {
  return (
    <svg className="bar">
      <defs>
        <linearGradient id="myGradient" gradientTransform="rotate(90)">
          <stop offset="1%" stopColor="rgba(30, 213, 169)" />
          <stop offset="99%" stopColor="rgba(255, 255, 255)" />
        </linearGradient>
      </defs>
      <rect
        className="bar-1"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-2"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-3"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-4"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-5"
        ry="5"
        y="0"
        height="150"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-6"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-7"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-8"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-9"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-10"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-11"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-12"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-13"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-14"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-15"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-16"
        ry="5"
        y="60"
        height="90"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-17"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-18"
        ry="5"
        y="50"
        height="100"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-19"
        ry="5"
        y="60"
        height="90"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-20"
        ry="5"
        y="70"
        height="80"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-21"
        ry="5"
        y="55"
        height="95"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-22"
        ry="5"
        y="60"
        height="90"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-23"
        ry="5"
        y="70"
        height="80"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-24"
        ry="5"
        y="50"
        height="100"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-25"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-26"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-27"
        ry="5"
        y="0"
        height="150"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-28"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-29"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-30"
        ry="5"
        y="50"
        height="100"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-31"
        ry="5"
        y="60"
        height="90"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-32"
        ry="5"
        y="70"
        height="80"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-33"
        ry="5"
        y="55"
        height="95"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-34"
        ry="5"
        y="60"
        height="90"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-34"
        ry="5"
        y="70"
        height="80"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-35"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-36"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-37"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-38"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-39"
        ry="5"
        y="0"
        height="150"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-40"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-41"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-42"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-43"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-44"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-45"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-46"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-47"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-48"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-49"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-50"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-51"
        ry="5"
        y="0"
        height="150"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-52"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-53"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-54"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-55"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-56"
        ry="5"
        y="50"
        height="100"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-57"
        ry="5"
        y="70"
        height="80"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-58"
        ry="5"
        y="50"
        height="100"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-59"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-60"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-61"
        ry="5"
        y="0"
        height="150"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-62"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-63"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-64"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-65"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-66"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-67"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-68"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-69"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-70"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-71"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-72"
        ry="5"
        y="0"
        height="150"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-73"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-53"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-54"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-55"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-56"
        ry="5"
        y="50"
        height="100"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-57"
        ry="5"
        y="70"
        height="80"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-58"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-59"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-60"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-61"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-62"
        ry="5"
        y="0"
        height="150"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-63"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-64"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-65"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-66"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-67"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-68"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-69"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-70"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-71"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-72"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-73"
        ry="5"
        y="60"
        height="90"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-74"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-75"
        ry="5"
        y="50"
        height="100"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-76"
        ry="5"
        y="60"
        height="90"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-77"
        ry="5"
        y="70"
        height="80"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-78"
        ry="5"
        y="55"
        height="95"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-79"
        ry="5"
        y="60"
        height="90"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-80"
        ry="5"
        y="70"
        height="80"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-81"
        ry="5"
        y="50"
        height="100"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-82"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-83"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-84"
        ry="5"
        y="0"
        height="150"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-85"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-86"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-87"
        ry="5"
        y="50"
        height="100"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-88"
        ry="5"
        y="60"
        height="90"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-89"
        ry="5"
        y="70"
        height="80"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-90"
        ry="5"
        y="55"
        height="95"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-91"
        ry="5"
        y="60"
        height="90"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-92"
        ry="5"
        y="70"
        height="80"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-93"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-94"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-95"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-96"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-97"
        ry="5"
        y="0"
        height="150"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-98"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-99"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-100"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-101"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-102"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-103"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-104"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-105"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-106"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-107"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-108"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-109"
        ry="5"
        y="0"
        height="150"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-110"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-111"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-112"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-113"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-114"
        ry="5"
        y="50"
        height="100"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-115"
        ry="5"
        y="70"
        height="80"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-116"
        ry="5"
        y="50"
        height="100"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-117"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-118"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-119"
        ry="5"
        y="0"
        height="150"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-120"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-121"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-122"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-123"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-124"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-125"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-126"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-127"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-128"
        ry="5"
        y="0"
        height="150"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-129"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-130"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-131"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-132"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-133"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-134"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-135"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-136"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-137"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-138"
        ry="5"
        y="0"
        height="150"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-139"
        ry="5"
        y="10"
        height="140"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-140"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-141"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-142"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-143"
        ry="5"
        y="50"
        height="100"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-144"
        ry="5"
        y="70"
        height="80"
        fill="url('#myGradient')"
      ></rect>

      <rect
        className="bar-145"
        ry="5"
        y="40"
        height="110"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-146"
        ry="5"
        y="30"
        height="120"
        fill="url('#myGradient')"
      ></rect>
      <rect
        className="bar-147"
        ry="5"
        y="20"
        height="130"
        fill="url('#myGradient')"
      ></rect>
    </svg>
  );
};

export default Bar;
